# vim:fileencoding=utf-8

background_blur 1
background_opacity 0.9
bold_font auto
bold_italic_font auto
disable_ligatures always
draw_minimal_borders yes
enable_audio_bell no
font_family family=monospace
font_size 12.0
initial_window_height 32c
initial_window_width 110c
italic_font auto
remember_window_size no
scrollback_lines 20000
scrollbar hovered

include dracula.conf
