[general]
live_config_reload = true

[window]
dimensions = { columns = 120, lines = 32 }
decorations = "Full"
opacity = 0.95
startup_mode = "Windowed"

[scrolling]
history = 20000

[font]
size = 12
normal = { family = "mononoki Nerd Font", style = "Regular" }


[colors.primary]
foreground = "#ffffff"
background = "#1e1e1e"

[colors.normal]
black = "#171421"
red = "#c01c28"
green = "#26a269"
yellow = "#a2734c"
blue = "#12488b"
magenta = "#a347ba"
cyan = "#2aa1b3"
white = "#d0cfcc"

[colors.bright]
black = "#5e5c64"
red = "#f66151"
green = "#33d17a"
yellow = "#e9ad0c"
blue = "#2a7bde"
magenta = "#c061cb"
cyan = "#33c7de"
white = "#ffffff"

[terminal]
shell = { program = "fish", args = ["--login"] }
